### ISSUE TITLE
WAやREの問題のリンクが表示されない

### ISSUE THREAD

**Issue by kmyk** [tallestorange/AtCoderProblems_4_Me#1]
以下のような感じです

![Screenshot_20190328-225022](https://user-images.githubusercontent.com/2203128/55162868-0fa1d680-51ac-11e9-8bb0-9ce2b21ee34e.png)
![Screenshot from 2019-03-28 22-47-07](https://user-images.githubusercontent.com/2203128/55162624-8be7ea00-51ab-11e9-9d25-78a626cfa9b0.png)

**Comment by tallestorange** [comment]
Bugfixしました。reloadするとちゃんと動くと思います。

<img width="1565" alt="a5" src="https://user-images.githubusercontent.com/13891795/55163496-42000380-51ad-11e9-82eb-619d23ae8b57.png">

**Comment by kmyk** [comment]
修正されてるの確認しました

**Comment by kmyk** [comment]
(https://tallestorange.github.io/AtCoderProblems_4_Me/ こっちはそのままになっちゃってるので、更新するか https://compro.192.works/ にリダイレクトさせておいた方がよさそうです)
